services:
  web:
    # 1. پوشه web روی کامپیوتر شما را به داخل کانتینر وصل می‌کند
    volumes:
      - ../web:/app

    # 2. دستور اجرا را به سرور توسعه (با قابلیت Hot Reloading) تغییر می‌دهد
    command: sh -c "npm install && npm run dev"

    # 3. یک پورت مستقیم برای دسترسی به محیط توسعه باز می‌کند
    ports:
      - "3000:3000"

  nginx:
    # 4. سرویس nginx را در حالت توسعه غیرفعال می‌کنیم چون به آن نیازی نداریم
    image: alpine
    command: "true"
